# Generated by Django 4.2.7 on 2023-11-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0002_alter_contato_options_alter_contato_datanascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('uf', models.CharField(choices=[('SP', 'Sao Paulo'), ('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais'), ('BA', 'Bahia')], max_length=2)),
            ],
        ),
    ]
